### ISSUE TITLE
Guide to Web Dev Project Update #1

### ISSUE THREAD

**Issue by ghost** [hackclub/guide-to-web-dev#1]
Recently I've been very busy to work on Hack Club's 🌐  `Guide-to-Web-Dev` 💻 because I got into Medical School! 🏥
 So the plan is to be making small updates to the project when I have time besides making pull requests for other repositories :octocat: , the first thing I'm going to be doing here is updating the introduction and the table of contents:

- Add the story of how I learned to code.
> Get into Web Dev.
- Write about the story of the web and the internet.
- Talk about DNS
- Explain HTML
- More....
- [x] Add links to other projects (Assembly Guide and Sprig). 

> Talk about Front-End Web Dev.
> > Decide what to do next after getting to this step. 

Wahoo! 🐠 

![image](https://user-images.githubusercontent.com/94091554/184570063-39f8a9a5-a3b8-4e19-8c92-a52f00748c3d.png)

**Comment by ghost** [comment]
This was the first update of the web dev project, I'm going to be making more when I get to make new things, so until next time! ⚡

**Comment by sampoder** [comment]
Love the update!
